#!/usr/bin/env bash

# Run docker containers if they are not up yet
if ! [[ $(docker ps | grep shlink_roadrunner) ]]; then
    docker compose up -d
fi

docker exec -it shlink_roadrunner /bin/sh -c "$*"
