title: 'Help wanted'
body:
  - type: input
    validations:
      required: true
    attributes:
      label: Shlink version
      placeholder: x.y.z
  - type: input
    validations:
      required: true
    attributes:
      label: PHP version
      placeholder: x.y.z
  - type: dropdown
    validations:
      required: true
    attributes:
      label: How do you serve Shlink
      options:
        - Self-hosted Apache
        - Self-hosted nginx
        - Self-hosted openswoole
        - Self-hosted RoadRunner
        - Openswoole Docker image
        - RoadRunner Docker image
        - Other (explain in summary)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Database engine
      options:
        - MySQL
        - MariaDB
        - PostgreSQL
        - MicrosoftSQL
        - SQLite
  - type: input
    validations:
      required: true
    attributes:
      label: Database version
      placeholder: x.y.z
  - type: markdown
    validations:
      required: true
    attributes:
      label: Summary
      value: '<!-- Describe your issue, question or request here. -->'

