<?php $this->layout('ShlinkCore::layout/default') ?>

<?php $this->start('title') ?>
    Invalid URL
<?php $this->end() ?>

<?php $this->start('stylesheets') ?>
    <style>
        p {margin-bottom: 20px;}
        body {text-align: center;}
    </style>
<?php $this->end() ?>

<?php $this->start('main') ?>
    <h1>Oops!</h1>
    <hr>
    <p>This short URL doesn\'t seem to be valid.</p>
    <p>Make sure you included all the characters, with no extra punctuation.</p>
<?php $this->end() ?>
