#!/bin/bash
set -ex

if [[ ${SOURCE_BRANCH} == 'develop' ]]; then
    SHLINK_RELEASE='latest'
else
    SHLINK_RELEASE=${SOURCE_BRANCH#?}
fi

docker build --build-arg SHLINK_VERSION=${SHLINK_RELEASE} -t ${IMAGE_NAME} .
