name: CI mutation tests
description: 'Runs mutation tests for certain tests suite'

inputs:
  test-group:
    required: true
    description: One of unit, db, api or cli
  php-version:
    required: true
    description: The PHP version to setup

runs:
  using: composite
  steps:
    - uses: './.github/actions/ci-setup'
      with:
        php-version: ${{ inputs.php-version }}
        php-extensions: openswoole-4.11.1
        extensions-cache-key: mutation-tests-extensions-${{ inputs.php-version }}-${{ inputs.test-group }}
    - uses: actions/download-artifact@v3
      with:
        name: coverage-${{ inputs.test-group }}
        path: build
    - name: Resolve infection args
      id: infection_args
      run: echo "::set-output name=args::--logger-github=false"
      #        TODO Try to filter mutation tests to improve execution times. Investigate why --git-diff-lines --git-diff-base=develop does not work
      #        run: |
      #          BRANCH="${GITHUB_REF#refs/heads/}" |
      #          if [[ $BRANCH == 'main' || $BRANCH == 'develop' ]]; then
      #            echo "::set-output name=args::--logger-github=false"
      #          else
      #            echo "::set-output name=args::--logger-github=false --git-diff-lines --git-diff-base=develop"
      #          fi;
      shell: bash
    - if: ${{ inputs.test-group == 'unit' }}
      run: composer infect:ci:unit -- ${{ steps.infection_args.outputs.args }}
      shell: bash
      env:
        INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
    - if: ${{ inputs.test-group != 'unit' }}
      run: composer infect:ci:${{ inputs.test-group }} -- ${{ steps.infection_args.outputs.args }}
      shell: bash
