<!DOCTYPE html>
<html lang="en">
  <head>
    <title><?= $this->section('title', '') ?> | URL shortener</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="shortcut icon" href="/favicon.ico">
    <style>
      html, body {height: 100%}
      .app {height: 100vh; display: flex; align-items: center; justify-content: center; flex-flow: column;}
    </style>
    <?= $this->section('stylesheets', '') ?>
  </head>
  <body>
    <div class="app">
      <main class="container">
        <?= $this->section('main', '') ?>
      </main>
    </div>
  </body>
</html>
